<div class="top-myaccount">
	<div class="top-myaccount-header">
		<a  rel="nofollow"   id="top-myaccount"  href="<?php echo $this->getUrl('customer/account') ?>" title="My Account"><?php echo $this->__('My Account') ?></a>
		<span class="top_arrow"></span>
	</div>
	<div class="drop-menu" style="display:none;">
		<a  rel="nofollow"   id="top-mydashboard"  href="<?php echo $this->getUrl('customer/account') ?>" title="My Dashboard"><?php echo $this->__('Account Dashboard') ?></a>
		<a  rel="nofollow"   id="top-mywishliist"  href="<?php echo $this->getUrl('wishlist') ?>" title="My Wishlist"><?php echo $this->__('My Wishlist') ?></a>
		<a  rel="nofollow"   id="top-myorder"  href="<?php echo $this->getUrl('sales/order/history') ?>" title="My Order"><?php echo $this->__('My Order') ?></a>
		<a  rel="nofollow"   id="top-myreviews"  href="<?php echo $this->getUrl('review/customer') ?>" title="My Reviews"><?php echo $this->__('My Product Reviews') ?></a>
		<a  rel="nofollow"   id="top-mytags"  href="<?php echo $this->getUrl('tag/customer') ?>" title="My Tags"><?php echo $this->__('My Tags') ?></a>
	</div>
</div>