<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<!-- 1-column -->
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>

    <!-- begin header -->
    <?php echo $this->getChildHtml('header') ?>
    <!-- end header -->

    <div class="wrapper">
        <?php echo $this->getChildHtml('global_notices') ?>
        <div class="page" id="all-content"> <!-- -->
            <div class="main-container col1-layout">
                <div class="main">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <div class="col-main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
    		<?php if ($this->getChildHtml('before_footer')): ?>
    		<div class="before_footer">
    			<?php echo $this->getChildHtml('before_footer') ?>
    			<div class="clear"></div>
    		</div>
    		<?php endif; ?>
            <?php echo $this->getChildHtml('before_body_end') ?>
        </div>
    </div>

    <!-- begin footer -->
    <?php echo $this->getChildHtml('footer') ?>
    <!-- end footer -->

    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
