<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<!-- 3-columns -->
<body <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <!-- begin header -->
    <?php echo $this->getChildHtml('header') ?>
    <!-- end header -->
    <div class="wrapper">
        <?php echo $this->getChildHtml('global_notices') ?>
        <div class="page" id="all-content">
            <div class="main-container col3-layout">
                <div class="main">
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <div class="col-wrapper">
                        <div class="col-main">
                            <?php echo $this->getChildHtml('global_messages') ?>
                            <?php echo $this->getChildHtml('content') ?>
                        </div>
                        <div class="col-left sidebar"><?php echo $this->getChildHtml('left') ?></div>
                    </div>
                    <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
                </div>
            </div>
    		<?php if ($this->getChildHtml('before_footer')): ?>
    		<div class="before_footer">
    			<?php echo $this->getChildHtml('before_footer') ?>
    			<div class="clear"></div>
    		</div>
    		<?php endif; ?>
            <?php echo $this->getChildHtml('before_body_end') ?>
    	</div>
    </div>
    <!-- begin footer -->
    <?php echo $this->getChildHtml('footer') ?>
    <!-- end footer -->
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
