<?php $_categories = $this->getStoreCategories() ?>
<?php if(count($_categories)): ?>

<SCRIPT src="/js/wcq.js" type="text/javascript"></SCRIPT>

<!--  分类导航条 -->
  <div class="nav-container sticky-container" id="header-nav">
    <div class="nav-container-inner">
      <?php echo $this->wcq_drawNavBar($_categories);?>
      <div class="clear"></div>
    </div>
  </div>
<!--  分类导航条 end -->

<SCRIPT src="/js/a.js" type="text/javascript"></SCRIPT>
<?php endif ?>