
<div class='footer-panel-container'>
    <div class='footer-panel'>
        <div class="footer-container">
            <div class="footer">
                <div class="footer_top">
        	        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_cms_links')->toHtml() ?>
        	        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('community-block')->toHtml() ?>
        		    <div class="clear"></div>
        	    </div><!-- end footer_top -->
                <div class="original-footer">
                     <?php echo $this->getChildHtml() ?>
        	    </div><!-- end original-footer-->
                <div class="footer_bottom">
        	        <address><?php echo $this->getCopyright() ?></address>
        	    </div><!-- end footer_bottom -->
            </div><!-- end footer -->
        </div><!-- end footer-container -->
    </div><!-- end footer-panel -->
</div><!-- end footer-panel-container -->

<div style="display:none;" class="nav_up" id="nav_up"></div>
<div style="display:none;" class="nav_down" id="nav_down"></div>
<script type="text/javascript">
    jQuery(function() {
	    var $elem = jQuery('#all-content');
				
		jQuery('#nav_up').fadeIn('slow');
		jQuery('#nav_down').fadeIn('slow');  
			
		jQuery(window).bind('scrollstart', function(){
			jQuery('#nav_up,#nav_down').stop().animate({'opacity':'0.2'});
		});
		jQuery(window).bind('scrollstop', function(){
			jQuery('#nav_up,#nav_down').stop().animate({'opacity':'0.7'});
		});
				
		jQuery('#nav_down').click(function (e) {
		  jQuery('html, body').animate({scrollTop: $elem.height()}, 800);
		});
		jQuery('#nav_up').click(function (e) {
			jQuery('html, body').animate({scrollTop: '0px'}, 800);
		});
    });
</script>