<script LANGUAGE="JavaScript"> 

var css_1024 ="<?php  echo $this->getSkinUrl('css/narrow.css');?>";
jQuery(window).resize(function(){
    if(window.innerWidth<=1200){
        jQuery("#width_adjust").attr("href", css_1024);
    }else{
        jQuery("#width_adjust").removeAttr("href", "");
    }
})
if (parseInt(screen.width)<= 1200) {
    jQuery("#width_adjust").attr("href", css_1024);
} else {
    jQuery("#width_adjust").removeAttr("href", "");
}
</script>
<div class='header-container-wrap'>
    <div class='header-container'>
        <div class="header">
            <div class="topbar">
        	    <!--<div class="home-link">
        	       <a href="<?php #echo $this->getUrl('')?>"><?php #echo $this->__('Home') ?></a>
        	    </div>-->
        	    <?php #echo $this->getChildHtml('store_language') ?>
        	    <?php #echo $this->getChildHtml('top_currency') ?>
        		<!--<span class="livechat">
        			<?php #echo $this->getLayout()->createBlock('cms/block')->setBlockId('livechat')->toHtml() ?>
        		</span>-->
        		<?php
                    echo $this->getChildHtml('top-myaccount');
                    echo $this->getChildHtml('mini_login');
                ?> 
            <!--<span class="welcome-msg"><?php #echo $this->getWelcome() ?> <?php #echo $this->getAdditionalHtml() ?></span>-->
            </div><!-- end topbar -->
            <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>

            <div class="quick-access">
                <div class="quick-access-left">
                   <?php echo $this->getChildHtml('topSearch') ?>
        	       <?php echo $this->getChildHtml('searchTerm') ?>
                </div><!-- end quick-access-left -->
                <div class="quick-access-right">
                    <?php echo $this->getChildHtml('top_cart') ?>
                </div><!-- end quick-access-right -->
            </div><!-- end quick-access -->
            <!-- begin topContainer -->
            <?php echo $this->getChildHtml('topContainer'); ?>
            <!-- end topContainer -->
            <div class="clear"></div>
        </div><!-- header -->
            <!-- begin topMenu -->
            <?php echo $this->getChildHtml('topMenu') ?>
            <!--  end topMenu  -->
    </div><!-- end header-container -->
</div><!-- header-container-wrap -->
